### ISSUE TITLE
KeyError: 'A100' When trying to return any data

### ISSUE THREAD

**Issue by BoredMind** [ttumiel/cloud-pricing#1]
This script is exactly what I'm looking for but it fails when trying to return any data now.  Is this something you might be able to fix?

> 
> cloud-pricing --cpus 32 --ram 244
> Namespace(cpus=32, gpus=0, ram=244, gpuram=10, verbose=False, n=10, unk_price=False, out=None, spot=False)
> Downloading latest Azure data...
> Traceback (most recent call last):
>   File "/usr/local/bin/cloud-pricing", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.9/site-packages/cloud_pricing/main.py", line 30, in main
>     proc = CloudProcessor()
>   File "/usr/local/lib/python3.9/site-packages/cloud_pricing/data/core.py", line 18, in __init__
>     self._tables.append(t())
>   File "/usr/local/lib/python3.9/site-packages/cloud_pricing/data/azure.py", line 22, in __init__
>     super().__init__(table_name)
>   File "/usr/local/lib/python3.9/site-packages/cloud_pricing/data/core.py", line 37, in __init__
>     self.setup()
>   File "/usr/local/lib/python3.9/site-packages/cloud_pricing/data/azure.py", line 86, in setup
>     gpu_ram = np.array([self.azure_gpus_ram[gpu_name] for gpu_name in gpu_names])
>   File "/usr/local/lib/python3.9/site-packages/cloud_pricing/data/azure.py", line 86, in <listcomp>
>     gpu_ram = np.array([self.azure_gpus_ram[gpu_name] for gpu_name in gpu_names])
> KeyError: 'A100'
> 

Thank you!

**Comment by ttumiel** [comment]
No problem. Seems like azure added new A100 instances. Should be working now.
